### ISSUE TITLE
Change http links to https?

### ISSUE THREAD

**Issue by wireguy** [lauragift21/awesome-learning-resources#53]

**Comment by lauragift21** [comment]
Hi 👋Where exactly do you want to make these changes?

**Comment by wireguy** [comment]
The first link in readme.md is
Manifesto for Agile Software Development    
agilemanifesto.org/     (no web protocol specified)
which defaults to http://   (not using https://)

Some sites, take care of making the default https://,  like
Oracle APEX Community
community.oracle.com/community/technology_network_community/database/developer-tools/application_express
That site defaults to https://,  so no change is necessary (but it would be clearer if you hover over the link)

Other sites, like
New Coder 
newcoder.io
default to http://,   but don't have a security certificate setup.
This will cause newer browsers, like Chrome to show a message 'Your connection is not private' if you change the link to https://
This allows the end user make their own decision about the link.

**Comment by lauragift21** [comment]
Alright thanks! I'll review them and update. In the meantime, if this is something you will like to take on I'll appreciate that too.
