### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [lauragift21/awesome-learning-resources#7]
I think the Table of Contents and topic headings should be alphabetically arranged, so it's easy to find stuff based on the topic.

It can also be added to the Contributing Guidelines that contributors follow this pattern.

Also, it would be nice if there's some automated way to check for this before PR is merged. (Don't mind my big mouth. 😊)

**Comment by lauragift21** [comment]
Thanks for suggesting. Yeah, I think having it arranged automatically would be nice. Also if you want t take a stab at it that's fine too :blush:
